{% set name = "sig-decomp" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sig_decomp-{{ version }}.tar.gz
  sha256: 756569154377071640f295aead8bbd43b042269495b1e7404bea9b0353220f95

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.6
    - numpy
    - pandas
    - scipy
    - matplotlib-base
    - cvxpy
    - scikit-learn
    - qss
    - clarabel

test:
  imports:
    - gfosd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sig-decomp/
  summary: Optimzation-based signal decomposition
  dev_url: https://github.com/cvxgrp/signal-decomposition
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pluflou
